<div class="img-sec" style="margin: 0px 0px 15px;display: table;width: 100%;text-align: center;border-bottom: 1px solid #000;padding-bottom: 10px;">
	<div class="last" style="background: #000;text-align: center;display: table-cell;vertical-align: middle;width: 50%;padding: 0 25px;">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."wysiwyg/newsletter/last1.png" ?>" style="width: 100%" />
		<div class="img-detail" style="padding: 0px 5px;text-align: center;">
			<p style="font-size: 12px;margin: 0px;color: #fff;">Up to 50% off over 1000 beauty steals until stocks last. Miss it and weep!</p>
			<a href="#" style="padding: 6px 11px;color: #000;text-transform: uppercase;background: #fff;text-decoration: none;display: inline-block;max-width: 150px;width: 100%;margin: 10px; 0px">GO, GO, GO >></a>
		</div>
	</div>
	<div style="">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."wysiwyg/newsletter/last2.gif" ?>" style="width: 100%;display: table-cell;vertical-align: middle;" />
	</div>
</div>