<div class="intro" style="display: inline-block;width: 100%;border-bottom: 1px solid #000;padding-bottom: 5px;margin-bottom: 10px;">
	<div style="width: 100%;text-align: center;">
		<a href="#" style="color: #000;font-size: 22px;font-weight: bold;display: block;text-decoration: none;">INTRODUCING</a>
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."wysiwyg/newsletter/fourth.png" ?>"/>
		<div class="img-detail" style="padding: 0px 5px;text-align: center;">
			<p style="font-size: 12px;margin: 0px;">OBESI BASTARDI.</p>
			<a href="#" style="padding: 6px 11px;color: #FFF;text-transform: uppercase;background: #000;text-decoration: none;display: inline-block;max-width: 150px;width: 100%;margin: 10px; 0px">Shop Now>></a>
		</div>
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."wysiwyg/newsletter/fifth.jpg" ?>" style="width: 100%; "/>
	</div>
</div>