<div class="img-sec" style="margin: 0px 0px 20px;display: inline-block;text-align: center;">
	<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."wysiwyg/newsletter/1.png" ?>" style="width: 100%;" />
	<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."wysiwyg/newsletter/first.jpg" ?>" style="width: 100%;" />
	<div class="img-detail" style="padding: 0px 5px;text-align: center;">
		<p style="font-size: 12px;margin: 0px;">The secret weapon of professional makeup artists in the entertainment industry, Paris-born Viseart offer pigment-rich palettes for a host of camera-ready looks.</p>
		<a href="#" style="padding: 6px 11px;color: #FFF;text-transform: uppercase;background: #000;text-decoration: none;display: inline-block;max-width: 150px;width: 100%;margin: 10px; 0px">Shop Now>></a>
	</div>
</div>

<div class="2-sec" style="margin: 0px 0px 20px;display: inline-block;border-bottom: 1px solid #000;text-align: center;">
	<div class="img-sec" style="float: left;width: 49%;margin-right: 1%;">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."wysiwyg/newsletter/second.jpg" ?>" style="width: 100%;" />
		<div class="img-detail" style="padding: 0px 5px;text-align: center;">
			<p style="font-size: 12px;margin: 0px;">WOW OBESI AL ROGO.</p>
			<a href="#" style="padding: 3px 11px;color: #000;text-transform: uppercase;background: transparent;border: 2px solid #000;text-decoration: none;display: inline-block;max-width: 170px;width: 100%;margin: 10px; 0px">Shop Now>></a>
		</div>
	</div>
	<div class="img-sec" style="width: 49%;float: right;">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."wysiwyg/newsletter/third.jpg" ?>" style="width: 100%;" />
		<div class="img-detail" style="padding: 0px 5px;text-align: center;">
			<p style="font-size: 12px;margin: 0px;">Introducing these handmade 100% rare soft silk lashes from bestselling lash brand Velour, for a ultra-lightweight, comfortable and long lasting wear.</p>
			<a href="#" style="padding: 3px 11px;color: #000;text-transform: uppercase;background: transparent;border: 2px solid #000;text-decoration: none;display: inline-block;max-width: 170px;width: 100%;margin: 10px; 0px">Shop Now>></a>
		</div>
	</div>
</div>
