<?php 
    $barcode = Mage::helper('giftvoucher')->getGeneralConfig('barcode_enable');
    $barcode_type = Mage::helper('giftvoucher')->getGeneralConfig('barcode_type');
    $url_barcode = '';
    if($barcode){
        if($barcode_type == 'code128') $url_barcode = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/barcode/default.png';
        else $url_barcode = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/barcode/qr.png';
    }
    if(!$template->getStyleColor()) $template->setStyleColor('orange');
    if(!$template->getTextColor()) $template->setTextColor('#2f2f2f');
    
    if ($template->getImages()) {
        $image = explode(',', $template->getImages());
        $image = $image[0];
    } else {
        $image = 'default.png';
    }
    $image = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/images/top/' . $image;
    
    if ($template->getData('background_img[value]')) {
        $background = $template->getData('background_img[value]');
    } else {
        $background = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/background/top/default.png';
    }

    if(Mage::getStoreConfig('giftvoucher/print_voucher/logo')) $logo = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/pdf/logo/'.Mage::getStoreConfig('giftvoucher/print_voucher/logo');
    else $logo = $this->getSkinUrl('images/logo_print.gif', array('_area'=>'frontend'));
?>
<style>
    .giftcard-text-color{
        color: <?php echo $template->getTextColor() ?>
    }
    .giftcard-style-color{
        color: <?php echo $template->getStyleColor() ?>
    }
</style>
<div id="giftcard-template-top" style="/*display:none*/overflow:hidden; width: 655px; height: 400px;font-size: 14px">
    <div class="giftcard-template-content-top giftcard-change-image" style="width: 655px; height: 150px; background-color: #FFFFFF;background-image: url(<?php echo $image ?>);background-position: center; background-repeat: no-repeat; background-size: 655px 150px">    </div>
    <div class="giftcard-template-content" style="width: 615px; height: 220px; padding: 20px; padding-top: 10px;background-color:#FFFFFF;background-image: url(<?php echo $background; ?>);background-position: center;background-repeat: no-repeat;background-size: 655px 250px">
        <div style="width: 615px; height: 75px;">
            <div style="width: 455px; height: 75px; font-size: 40px; font-style: italic;float: left">
                <div style="width: 175px; height: 50px; margin-top: 15px; background:url(<?php echo $logo ?>) center  no-repeat;background-size: contain; float: left"></div>
                <div class="giftcard-style-color giftcard-title" style="margin-left: 10px;width: 270px; margin-top: 10px; float: left; font-family: time new roman; line-height: 60px"><?php echo $template->getCaption() ?></div>
            </div>
            <div style="width: 160px; height: 65px; float: left; padding-top: 10px">
                <div  class="giftcard-text-color" style="text-align: right; width: 160px;">value</div>
                <div class="giftcard-style-color giftcard-price-change" style="width: 160px; text-align: right; font-size: 35px; font-weight: bold; font-family: time new roman; line-height: 45px">$100.00</div>
            </div>
        </div>
        <div style="width: 615px; height: 25px;margin-top: 5px;">
            <div style="width: 320px; height: 25px; padding-left: 5px; float: left;font-size: 16px;">
                <span style="width: 160px;margin-right: 20px">
                    <label  class="giftcard-text-color" for="giftcard-from" style="font-style: italic;font-family: time new roman">from:</label>
                    <span class="giftcard-style-color giftcard-send-from" style="">..........</span>
                </span>
                |
                <span style="width: 160px; margin-left: 20px">
                    <label  class="giftcard-text-color" for="giftcard-to" style="font-style: italic;font-family: time new roman">to: </label>
                    <span class="ggiftcard-style-color giftcard-send-to" style="">...........</span>
                </span>
            </div>
            <div style="width: 290px; float: left; text-align: right;font-size: 14px;">
                <span style="width: 290px;">
                    <label  class="giftcard-text-color">Card number</label>
                    <?php if($url_barcode != ''): ?>
                    &nbsp;<span class="giftcard-style-color" style="font-weight: bold; font-family: time new roman;">GIFT-XXXX-XXXX</span>
                    <?php endif; ?>
                </span>
            </div>
        </div>
        <div style="width: 615px; height: 120px;">
            <div style="overflow: hidden; float: left;width: 340px; height: 100px;margin-top: 20px; ">
                <div style="padding: 6px; padding-bottom: 14px; background: url(<?php echo $this->getSkinUrl('images/giftvoucher/box-message.png', array('_area'=>'frontend')) ?>) no-repeat;width: 328px; height: 80px;display:table-cell; vertical-align: middle"><p class="giftcard-text-color giftcard-custom-message" style="margin: 0"><?php echo $this->__('Write message here ...') ?></p></div>
            </div>
            <div style="float: left; width: 275px;text-align: right">
                <span style="width: 180px; height: 50px ">
                    <?php if($url_barcode != ''): ?>
                    <img src="<?php echo $url_barcode ?>" />
                    <?php else: ?>
                    <div class="giftcard-style-color" style="font-size: 24px;line-height: 35px; font-weight: bold;font-family: time new roman">GIFT-XXXX-XXXX</div>
                    <?php endif; ?>
                </span>
                <div style="height: 5px"></div>
                <div style="width: 260px; height: 65px; overflow: hidden; padding-left: 15px; margin-top: 5px;display:table-cell; vertical-align: bottom">
                    <p style="font-size: 11px; line-height: 16px; margin: 0" class="giftcard-text-color"><?php echo Mage::getSingleton('giftvoucher/giftvoucher')->getPrintNotes(); ?></p>
                </div>
            </div>
        </div>
    </div>
</div>