<?php
/**
 * Print Gift Card
 */
?>
<style>
    .print-notes{
        color: <?php echo $_styleColor ?>;
        text-decoration: none;
    }
    .print-font{
        font: 12px/1.55 Arial, Helvetica, sans-serif;
    }
</style>
<?php $_store = Mage::app()->getStore() ?>
<?php $_giftCards = $this->getGiftVouchers() ?>
<?php foreach ($_giftCards as $_giftCard):?>
<?php 
    $_template = $this->getGiftcardTemplate($_giftCard->getGiftcardTemplateId());
    $barcode = Mage::helper('giftvoucher')->getGeneralConfig('barcode_enable');
    $barcode_type = Mage::helper('giftvoucher')->getGeneralConfig('barcode_type');
    $url_barcode = '';
    $qr = new Magestore_Giftvoucher_QRCode($_giftCard->getGiftCode());
    if($barcode){
        $resizeImage = FALSE;
        if($barcode_type == 'code128'){
            $url_barcode = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/barcode/'.$_giftCard->getGiftCode().'.png';
            $imageUrl = Mage::getBaseDir('media') . DS . 'giftvoucher' . DS . 'template' . DS . 'barcode' . DS . $_giftCard->getGiftCode().'.png';
            $imageObj = new Varien_Image($imageUrl);
            if($imageObj->getOriginalWidth() > 200) $resizeImage = true;
        }
        else $url_barcode = $qr->getResult();
    }
    
    if(!$_template->getStyleColor()) $_template->setStyleColor('orange');
    if(!$_template->getTextColor()) $_template->setTextColor('#2f2f2f');
    $_styleColor = $_template->getStyleColor();
    $_textColor = $_template->getTextColor();
    if(!$_giftCard->getGiftcardTemplateImage()) $_giftCard->setGiftcardTemplateImage('default.png');
    if(!$_template->getBackgroundImg()) $_template->getBackgroundImg('default.png');
?>
<?php if($_template->getDesignPattern() == Magestore_Giftvoucher_Model_Designpattern::PATTERN_TOP): ?>
<div style="position: relative; z-index: 12;overflow:hidden; width: 655px; height: 400px;font-size: 14px; margin-bottom: 60px">
    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/images/top/'.$_giftCard->getGiftcardTemplateImage() ?>" width="655" height="150" />
    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/background/top/'.$_template->getBackgroundImg() ?>" width="655" height="250" style="z-index:10; position: absolute; top: 150; left: 0" />
    <div style="z-index: 12; position: relative; width: 615px; height: 220px; padding: 20px; padding-top: 10px;">
        <div style="width: 615px; height: 80px;">
            <div style="width: 455px; height: 75px; font-size: 40px; font-style: italic; color: orange;float: left">
                <div style="width: 175px; height: 75px; float: left; padding-top: 9px">
                    <img src="<?php echo $_giftCard->getPrintLogo() ? $_giftCard->getPrintLogo() : $this->getSkinUrl('images/logo_print.gif', array('_area'=>'frontend')) ?>" height="50" width="auto" alt="<?php echo $_store->getFrontendName() ?>" title="<?php echo $_store->getFrontendName() ?>" />
                </div>
                <div style="margin-left: 10px;width: 270px; padding-top: 10px; float: left; color: <?php echo $_styleColor ?>"><span><?php echo $_template->getCaption() ?></span></div>
            </div>
            <div style="width: 160px; height: 65px; float: left; padding-top: 10px;">
                <div class="print-font" style="text-align: right; width: 160px;height: 21px; color: <?php echo $_textColor ?>"><span style="float: right"><?php echo Mage::helper('giftvoucher')->__('Value') ?></span></div>
                <div style="width: 160px; text-align: right; font-size: 30px;height: 50px; color: <?php echo $_styleColor ?>; font-weight: bold"><span style="float: right"><?php echo Mage::helper('core')->formatPrice($_giftCard->getBalance()) ?></span></div>
            </div>
        </div>
        <div style="width: 615px; height: 25px;">
            <div style="width: 320px; height: 25px; padding-left: 5px; float: left;font-size: 16px;">
                <span style="width: 160px;margin-right: 20px">
                    <label for="giftcard-from" style="font-style: italic;color: <?php echo $_textColor ?>"><?php echo Mage::helper('giftvoucher')->__('from:') ?></label>
                    <span class="giftcard-text-color giftcard-send-form print-font" style="font-weight: bold; color: <?php echo $_styleColor ?>"><?php echo $_giftCard->getCustomerName() ?></span>
                </span>
                |
                <span style="width: 160px; margin-left: 20px">
                    <label for="giftcard-to" style="font-style: italic;color: <?php echo $_textColor ?>"><?php echo Mage::helper('giftvoucher')->__('to:') ?> </label>
                    <span class="giftcard-text-color giftcard-send-to print-font" style="font-weight: bold; color: <?php echo $_styleColor ?>"><?php echo $_giftCard->getRecipientName() ?></span>
                </span>
            </div>
            <div style="width: 290px; float: left; text-align: right;font-size: 14px;">
                <span style="width: 290px;">
                    <?php if($url_barcode != ''): ?><span style="color: <?php echo $_styleColor ?>; font-weight: bold; float: right"><span  class="print-font" style="font-weight: normal; color: <?php echo $_textColor ?>"><?php echo Mage::helper('giftvoucher')->__('Gift Card Number') ?>:&nbsp;</span><?php echo $_giftCard->getGiftCode() ?></span><?php else: ?>
                    <span style="float: right" class="print-font" ><?php echo Mage::helper('giftvoucher')->__('Gift Card Number') ?></span><?php endif; ?>
                </span>
            </div>
        </div>
        <div style="position: relative; width: 615px; height: 120px;">
            <div style="float: left;width: 340px; height: 100px;margin-top: 20px; ">
                <img src="<?php echo $this->getSkinUrl('images/giftvoucher/box-message.png', array('_area'=>'frontend')) ?>" width="340" height="100" style="z-index: -1; position: absolute; top: 20px; left: 0" />
                <div style="padding: 6px; padding-bottom: 14px; padding-top: 3px;  width: 328px; height: 80px;display:table-cell; vertical-align: middle;color: <?php echo $_textColor ?>"><pre  class="print-font" style="margin: 0; white-space: pre-wrap; max-height: 85px; overflow: hidden; font-size: 11px"><?php echo $_giftCard->getMessage() ?></pre></div>
            </div>
            <div style="float: left; width: 275px;text-align: right">
                <span style="width: 275px; height: 50px; float: right ">
                    <?php if($url_barcode != ''): ?><img src="<?php echo $url_barcode ?>" <?php if($resizeImage) echo 'width="200" height="50"' ?> style="float: right"/><?php else: ?>
                    <span style="color: orange; font-weight: bold; font-size: 22px; line-height: 30px; float: right"><?php echo $_giftCard->getGiftCode() ?></span><?php endif; ?>
                </span>
                <div style="height: 5px"></div>
                <div style="width: 260px; height: 65px; font-size: 11px; line-height: 16px; overflow: hidden; padding-left: 15px; margin-top: 5px;display:table-cell; vertical-align: bottom">
                    <span style="width: 260px">
                        <span class="print-font"  style="float: right; color: <?php echo $_textColor ?>"><?php echo $_giftCard->getPrintNotes() ?></span>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
<?php elseif($_template->getDesignPattern() == Magestore_Giftvoucher_Model_Designpattern::PATTERN_CENTER): ?>
<div id="giftcard-template-back" style="position: relative">
    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/images/'.$_giftCard->getGiftcardTemplateImage() ?>" width="655" height="400" style="z-index:10; position: absolute; top: 0; left: 0" />
    <div class="giftcard-change-image" style="z-index: 12; position: relative; overflow: hidden; width: 655px; padding-top: 35px; height: 400px; font-size: 14px; margin-bottom: 60px">
        <div style="position: relative; height: 75px; font-size: 40px; font-style: italic;">
            <div style="margin-left: 50px; width: 185px; height: 60px; float: left; padding-top: 5px">
                <img src="<?php echo $_giftCard->getPrintLogo() ? $_giftCard->getPrintLogo() : $this->getSkinUrl('images/logo_print.gif', array('_area'=>'frontend')) ?>" height="50" width="auto" />
            </div>
            <div class="giftcard-style-color giftcard-title" style="margin-left: 10px; padding-top: 7px; float: left;color: <?php echo $_styleColor ?>"><span><?php echo $_template->getCaption() ?></span></div>
        </div>
        <div style="position: relative; width: 655px; height: 25px; font-size: 16px;line-height: 16px">
            <div style="width: 308px; float: left; text-align: right; padding-right: 20px">
                <span class="giftcard-text-color giftcard-send-form print-font" id='giftcard-from' style="color: <?php echo $_styleColor ?>;font-weight: bold; float: right"><span style="font-weight: normal; color: <?php echo $_textColor ?>; font-style: italic;"><?php echo Mage::helper('giftvoucher')->__('from:') ?></span><?php echo $_giftCard->getCustomerName() ?></span>
            </div><div style="float:left">|</div>
            <div style="width: 305px; float: left; padding-left: 19px; height: 20px; padding-bottom: 5px">
                <label for="giftcard-to" style="font-style: italic;color: <?php echo $_textColor ?>"><?php echo Mage::helper('giftvoucher')->__('to:') ?> </label>
                <span class="giftcard-text-color giftcard-send-to print-font" id='giftcard-to' style="color: <?php echo $_styleColor ?>;font-weight: bold"><?php echo $_giftCard->getRecipientName() ?></span>
            </div>
        </div>
        <div style="position: relative; width: 600px; height: 100px;margin: 0 auto; margin-top: 5px;">
            <img src="<?php echo $this->getSkinUrl('images/giftvoucher/box-message2.png', array('_area'=>'frontend')) ?>" width="600" height="100" style="z-index:-1; position: absolute; top: 0; left: 0" />
            <div style=" padding: 6px; padding-bottom: 16px; padding-top: 3px;  width: 588px; height: 78px; display:table-cell; vertical-align: middle;"><pre class="giftcard-text-color giftcard-custom-message print-font" style="margin: 0;white-space: pre-wrap; color: <?php echo $_textColor ?>; max-height: 85px; overflow: hidden; font-size: 11px"><?php echo $_giftCard->getMessage() ?></pre></div>
        </div>
        <div style="position: relative;margin: 0 0 10px 0;width: 655px; height: 75px; ">
            <div style="width: 177px; height: 75px;float: left; padding-left: 150px">
                <div class="print-font" style="height: 21px;color: <?php echo $_textColor ?>"><?php echo Mage::helper('giftvoucher')->__('Value') ?></div>
                <div class="giftcard-style-color giftcard-price-change" style="font-size: 30px; height: 50px;color: <?php echo $_styleColor ?>; font-weight: bold"><?php echo Mage::helper('core')->formatPrice($_giftCard->getBalance()) ?></div>
            </div>
            <div style="width: 328px; height: 75px;float: left">            
                <?php if($url_barcode != ''): ?>
                <div>
                    <label class="print-font" style="color: <?php echo $_textColor ?>"><?php echo Mage::helper('giftvoucher')->__('Gift Card Number') ?>:</label>
                    <span class="giftcard-style-color" style="color: <?php echo $_styleColor ?>; font-weight: bold"><?php echo $_giftCard->getGiftCode() ?></span>
                </div>
                <span style="width: 180px; height: 50px "><img src="<?php echo $url_barcode ?>" <?php if($resizeImage) echo 'width="200" height="50"' ?> /></span>
                <?php else: ?>
                <div class="print-font" style="color: <?php echo $_textColor ?>"><?php echo Mage::helper('giftvoucher')->__('Gift Card Number') ?></div>
                <div class="giftcard-style-color giftcard-price-change" style="font-size: 26px; line-height: 52px; color: orange; font-weight: bold"><?php echo $_giftCard->getGiftCode() ?></div>
                <?php endif; ?>
            </div>
        </div>
        <div style="position: relative; width: 655px; height: 45px;padding: 5px 0; overflow: hidden;background: #FFF;opacity: 0.7; filter: alpha(opacity= 70); text-align: center;display:table-cell; vertical-align: middle">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/pdf/white-background.png'; ?>" width="655" height="55" style="z-index: -1;position: absolute; top: 0; left: 0; opacity:0.7;filter: alpha(opacity= 70);" />
            <div style="width: 450px; margin: 0 auto;">
                <p class="print-font" style="font-size: 11px;line-height: 15px; margin: 0;color: <?php echo $_textColor ?>"><?php echo $_giftCard->getPrintNotes() ?></p>
            </div>
        </div>    
    </div>
</div>
<?php else: ?>
<div id="giftcard-template-left" style="z-index: 12;position: relative; overflow:hidden; width: 655px; height: 400px;font-size: 14px; margin-bottom: 60px">
    <div class="giftcard-template-content-left giftcard-change-image" style="position: relative; width: 275px; height: 400px; float: left;padding-top: 300px">
        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/images/left/'.$_giftCard->getGiftcardTemplateImage() ?>" width="275" height="400" style="z-index:10; position: absolute; top: 0; left: 0" />
        <div style="position:relative; width: 275px; height: 75px;z-index: 12; background: #fff; display: table-cell; vertical-align: middle; text-align: center">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/pdf/white-background.png'; ?>" width="273" height="75" style="z-index: -1;position: absolute; top: 0; left: 0;" />
            <img src="<?php echo $_giftCard->getPrintLogo() ? $_giftCard->getPrintLogo() : $this->getSkinUrl('images/logo_print.gif', array('_area'=>'frontend')) ?>" width="auto" height="50" style="max-width: 175px"/>
        </div>
    </div>
    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/background/left/'.$_template->getBackgroundImg() ?>" width="380" height="400" style="z-index:10; position: absolute; top: 0; left: 275px" />
    <div class="giftcard-template-content" style="z-index: 12;position: relative;width: 340px; height: 360px; padding: 20px;float: left">
        <div class="giftcard-style-color giftcard-title" style="width: 340px; height: 60px; font-size: 40px; font-style: italic; color: <?php echo $_styleColor ?>">
            <?php echo $_template->getCaption() ?>
        </div>
        <div style="width: 340px;font-size: 16px; height: 35px">
            <span style="width: 170px;margin-right: 30px">
                <label for="giftcard-from" style="font-style: italic;color: <?php echo $_textColor ?>"><?php echo Mage::helper('giftvoucher')->__('from:') ?></label>
                <span class="giftcard-text-color giftcard-send-from print-font" style="font-weight: bold; color: <?php echo $_styleColor ?>"><?php echo $_giftCard->getCustomerName() ?></span>
            </span>
            |
            <span style="width: 170px; margin-left: 30px">
                <label for="giftcard-to" style="font-style: italic;color: <?php echo $_textColor ?>"><?php echo Mage::helper('giftvoucher')->__('to:') ?> </label>
                <span class="giftcard-text-color giftcard-send-to print-font" style="font-weight: bold; color: <?php echo $_styleColor ?>"><?php echo $_giftCard->getRecipientName() ?></span>
            </span>
        </div>
        <div style="position: relative; width: 340px; height: 108px; ">
            <img src="<?php echo $this->getSkinUrl('images/giftvoucher/box-message.png', array('_area'=>'frontend')) ?>" width="340" height="100" style="z-index:-1; position: absolute; top: 0; left: 0" />
            <div style="padding: 6px; padding-bottom: 14px; padding-top: 3px; width: 328px; height: 80px;display:table-cell; vertical-align: middle"><pre class="giftcard-text-color giftcard-custom-message print-font" style="white-space: pre-wrap; margin: 0;color: <?php echo $_textColor ?>; max-height: 85px; overflow: hidden; font-size: 11px"><?php echo $_giftCard->getMessage() ?></pre></div>
        </div>
        <div style="width: 340px;height: 21px;">
            <span class="print-font" style="width: 55px; float: left;color: <?php echo $_textColor ?>"><?php echo Mage::helper('giftvoucher')->__('Value') ?></span>
            <span style="width: 285px; float: right; text-align: right">
                <?php if($url_barcode !=''): ?><span style=" color: <?php echo $_styleColor ?>; font-weight: bold; float: right"><span class="print-font" style="font-weight: normal;  color: <?php echo $_textColor ?>"><?php echo Mage::helper('giftvoucher')->__('Gift Card Number') ?>:&nbsp;</span><?php echo $_giftCard->getGiftCode() ?></span><?php else: ?>
                <span class="print-font"  style="font-weight: normal; float: right"><?php echo Mage::helper('giftvoucher')->__('Gift Card Number') ?></span><?php endif; ?>
            </span>
        </div>
        <div style="width: 340px;height: 70px">
            <span class="giftcard-style-color giftcard-price-change" style="width: 130px; float: left; font-size: 25px;  color: <?php echo $_styleColor ?>; font-weight: bold"><?php echo Mage::helper('core')->formatPrice($_giftCard->getBalance()) ?></span>
            <div style="width: 210px; float: right; text-align: right">
                <?php if($url_barcode != ''): ?>
                <img src="<?php echo $url_barcode ?>" <?php if($resizeImage) echo 'width="200" height="50"' ?> style="float: right"/>
                <?php else: ?>
                <span style=" color: <?php echo $_styleColor ?>; font-weight: bold; font-size: 20px; line-height: 45px; float: right"><?php echo $_giftCard->getGiftCode() ?></span>
                <?php endif; ?>
            </div>
        </div>
        <div style="width: 340px;height: 65px; overflow: hidden; text-align: left; display:table-cell; vertical-align: bottom">
            <p class="print-font" style="font-size: 11px;line-height: 16px; margin: 0;color: <?php echo $_textColor ?>"><?php echo $_giftCard->getPrintNotes() ?></p>
        </div>
    </div>
</div>
<?php endif; ?>

<script type="text/javascript">window.print();</script>
<?php endforeach;?>