<?php
/**
 * Gift Voucher product media template
 */
?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
$templates = Mage::getBlockSingleton('giftvoucher/product_view')->getAvailableTemplate();
if (count($templates)):
    ?>
    <div class="giftcard-product-media">
        <div class = "background-popup" style="cursor: pointer; -moz-transform-origin: left top;" onclick="getPreview()">
            <?php include 'template/background.phtml'; ?>
        </div>
        <div class = "top-popup" style="cursor: pointer; -moz-transform-origin: left top;" onclick="getPreview()">
            <?php include 'template/top.phtml'; ?>
        </div>
        <div class = "left-popup" style="cursor: pointer; -moz-transform-origin: left top;" onclick="getPreview()">
            <?php
            include 'template/left.phtml';
            ?>
        </div>
    </div>
    <!--    Popup   -->
    <div id="giftcard-preview-template" style="display: none; width: 100%; ">
        <div style="position: absolute; cursor: pointer; top: -18px; right: -15px; width: 35px; height: 35px; background: transparent url(<?php echo $this->getSkinUrl('images/giftvoucher/close.png') ?>)" onclick="winPopupPreview.hide();"></div>
        <div id="giftcard-preview-template-content"></div>
    </div>
    <script type="text/javascript">
        $('giftcard-template-back').hide();
        $('giftcard-template-top').hide();
        $('giftcard-template-left').hide();
        var winPopupPreview = new Window({windowClassName: 'giftcard-preview-template-dialog', title: 'Giftcard Template', zIndex: 100, width: 655, height: 400, minimizable: false, maximizable: false, showEffectOptions: {duration: 0.4}, hideEffectOptions: {duration: 0.4}, resizable: true, destroyOnClose: true, recenterAuto: false});
        function getPreview() {
            if ($('giftcard-template-back').style.display != 'none')
                $('giftcard-preview-template-content').innerHTML = $('giftcard-template-back').innerHTML;
            else if ($('giftcard-template-top').style.display != 'none')
                $('giftcard-preview-template-content').innerHTML = $('giftcard-template-top').innerHTML;
            else
                $('giftcard-preview-template-content').innerHTML = $('giftcard-template-left').innerHTML;
            winPopupPreview.setContent('giftcard-preview-template');
            winPopupPreview.showCenter(true);
            $('overlay_modal').observe('click', function(event) {
                winPopupPreview.hide();
            });
        }
    </script>
    <?php
else:
    ?>
    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
        <p class="product-image product-image-zoom">
            <?php
            $_img = '<img id="image" src="' . $this->helper('catalog/image')->init($_product, 'image') . '" alt="' . $this->escapeHtml($this->getImageLabel()) . '" title="' . $this->escapeHtml($this->getImageLabel()) . '" />';
            echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
        <p class="zoom-notice" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
        <div class="zoom">
            <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
            <div id="track">
                <div id="handle"></div>
            </div>
            <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
        </div>
        <script type="text/javascript">
        //<![CDATA[
            Event.observe(window, 'load', function() {
                product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
            });
        //]]>
        </script>
    <?php else: ?>
        <p class="product-image">
            <?php
            $_img = '<img src="' . $this->helper('catalog/image')->init($_product, 'image')->resize(265) . '" alt="' . $this->escapeHtml($this->getImageLabel()) . '" title="' . $this->escapeHtml($this->getImageLabel()) . '" />';
            echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
    <?php endif; ?>
    <?php if (count($this->getGalleryImages()) > 0): ?>
        <div class="more-views">
            <h2><?php echo $this->__('More Views') ?></h2>
            <ul>
                <?php foreach ($this->getGalleryImages() as $_image): ?>
                    <li>
                        <a href="#" onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');
                                return false;" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" width="56" height="56" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" /></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
    <!--<div class="giftvoucher-media">
        <div class="giftmedia" id="giftmedia" style="display:none;"><pre id="giftmedia-pre"></pre></div>
        <div class="giftmedia-image">
    <?php
//            $_image = $this->helper('catalog/image')->init($_product, 'image');
//            $_height = 261 * $_image->getOriginalHeight() / $_image->getOriginalWidth();
//            $_image->resize(261,$_height);
//            $_img = '<img src="'.$_image.'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
//            echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
        </div>
    </div>-->
<?php
endif;
?>
<script type="text/javascript">
    var $giftcard = jQuery.noConflict();
    var giftcardWidth1 = $giftcard('#giftcard-template-left').innerWidth();
    var containerWidth = $giftcard('.container').innerWidth();
    var width1 = (100 * (giftcardWidth1 / containerWidth));
    // alert(width1);
    var widthFirst = (100 * (580 / 1200));

    if (width1 < 40) {
        $giftcard('.giftcard-template-content-left').addClass("hidden-content-left");
        $giftcard('.giftcard-change-image-background-popup').addClass("hidden-content-background");
        $giftcard('.giftcard-template-content').addClass("hidden-content");
        $giftcard('.giftcard-template-content-left').addClass("hidden-change-image");
        $giftcard('#giftcard-template-top').addClass("hidden-giftcard-template-top-1");
        $giftcard('.giftcard-template-content-temp2').addClass("hidden-giftcard-content-temp2");

    } else {
        if (width1 > 50 && width1 <= 100) {
            $giftcard('#giftcard-template-left').addClass("hidden-giftcard-content-left");
            $giftcard('.giftcard-template-content-left').addClass("hidden-content-left");
            $giftcard('.giftcard-change-image-background-popup').addClass("hidden-giftcard-content-background");
            $giftcard('.giftcard-template-content').addClass("hidden-content");
            $giftcard('.giftcard-template-content-left').addClass("hidden-change-image")
            $giftcard('#giftcard-template-top').addClass("hidden-giftcard-template-top-2");
            $giftcard('.giftcard-change-image-background-popup').removeClass("hidden-content-background");
            $giftcard('#giftcard-template-top').removeClass("hidden-giftcard-template-top-1");
            $giftcard('.giftcard-template-content-temp2').addClass("hidden-giftcard-content-temp2");

        }
    }
    window.onresize = resize;
    function resize() {
        var giftcardWidth1 = $giftcard('#giftcard-template-left').innerWidth();
        var containerWidth = $giftcard('.container').innerWidth();
        var width1 = (100 * (giftcardWidth1 / containerWidth));
        // alert(width1);
        var widthFirst = (100 * (580 / 1200));

        if (width1 < 40) {
            $giftcard('.giftcard-template-content-left').addClass("hidden-content-left");
            $giftcard('.giftcard-change-image-background-popup').addClass("hidden-content-background");
            $giftcard('.giftcard-template-content').addClass("hidden-content");
            $giftcard('.giftcard-template-content-left').addClass("hidden-change-image");
            $giftcard('#giftcard-template-top').addClass("hidden-giftcard-template-top-1");
            $giftcard('.giftcard-template-content-temp2').addClass("hidden-giftcard-content-temp2");

        } else {
            if (width1 > 48 && width1 <= 100) {
                $giftcard('#giftcard-template-left').addClass("hidden-giftcard-content-left");
                $giftcard('.giftcard-template-content-left').addClass("hidden-content-left");
                $giftcard('.giftcard-change-image-background-popup').removeClass("hidden-content-background");
                $giftcard('.giftcard-change-image-background-popup').addClass("hidden-giftcard-content-background");
                $giftcard('.giftcard-template-content').addClass("hidden-content");
                $giftcard('.giftcard-template-content-left').addClass("hidden-change-image")
                $giftcard('#giftcard-template-top').addClass("hidden-giftcard-template-top-2");
                $giftcard('#giftcard-template-top').removeClass("hidden-giftcard-template-top-1");
                $giftcard('.giftcard-template-content-temp2').addClass("hidden-giftcard-content-temp2");
            }
        }

    }
</script>
