<?php if (Mage::getStoreConfig('onestepcheckout/general/suggest_address', Mage::app()->getStore()->getStoreId())): ?>
	<script type="text/javascript">
		// Leo
		function fillBillingAddress() {
			var place = autocompleteBilling.getPlace();
			var street, city, region_id, region, it_region_id, it_region, country, postal_code, sublocality;

			for (var i = 0; i < place.address_components.length; i++) {
				var addressType = place.address_components[i].types[0];
					if (addressType == 'street_number') {
						if (street)
							street += ' ' + place.address_components[i][componentBillingForm['street_number']];
						else
							street = place.address_components[i][componentBillingForm['street_number']];
					}
					if (addressType == 'route') {
						if (street)
							street += ' ' + place.address_components[i][componentBillingForm['route']];
						else
							street = place.address_components[i][componentBillingForm['route']];
					}
					if (addressType == 'locality')
						city = place.address_components[i][componentBillingForm['locality']];
					if (addressType == 'administrative_area_level_1') {
						region_id = place.address_components[i]['short_name'];
						region = place.address_components[i]['long_name'];
					}
					if (addressType == 'administrative_area_level_2') {
						it_region_id = place.address_components[i]['short_name'];
						it_region = place.address_components[i]['long_name'];
					}
					if (addressType == 'country')
						country = place.address_components[i][componentBillingForm['country']];
					if (addressType == 'postal_code')
						postal_code = place.address_components[i][componentBillingForm['postal_code']];
					if (addressType == 'sublocality_level_1')
						sublocality = place.address_components[i][componentBillingForm['sublocality_level_1']];
			}
			if(country == 'IT'){
				region = it_region;
				region_id = it_region_id;
			}
			fillAddress('billing', street, city, region_id, region, country, postal_code, sublocality);
		}
		
        function fillShippingAddress() {
            var place = autocompleteShipping.getPlace();
			var street, city, region_id, region, it_region_id, it_region, country, postal_code, sublocality;
            for (var i = 0; i < place.address_components.length; i++) {
                var addressType = place.address_components[i].types[0];
                    if (addressType == 'street_number') {
                        if (street)
                            street += ' ' + place.address_components[i][componentShippingForm['street_number']];
                        else
                            street = place.address_components[i][componentShippingForm['street_number']];
                    }
                    if (addressType == 'route') {
                        if (street)
                            street += ' ' + place.address_components[i][componentShippingForm['route']];
                        else
                            street = place.address_components[i][componentShippingForm['route']];
                    }
                    if (addressType == 'locality')
                        city = place.address_components[i][componentShippingForm['locality']];
                    if (addressType == 'administrative_area_level_1') {
                        region_id = place.address_components[i]['short_name'];
                        region = place.address_components[i]['long_name'];
                    }
					if (addressType == 'administrative_area_level_2') {
						it_region_id = place.address_components[i]['short_name'];
						it_region = place.address_components[i]['long_name'];
					}
                    if (addressType == 'country')
                        country = place.address_components[i][componentShippingForm['country']];
                    if (addressType == 'postal_code')
                        postal_code = place.address_components[i][componentShippingForm['postal_code']];
                    if (addressType == 'sublocality_level_1')
                        sublocality = place.address_components[i][componentShippingForm['sublocality_level_1']];
            
			}
			if(country == 'IT'){
				region = it_region;
				region_id = it_region_id;
			}
            fillAddress('shipping', street, city, region_id, region, country, postal_code, sublocality)
        }
        Event.observe(window, 'load', function() {
			$('one-step-checkout-form').on('keypress', function(e) {
			  var keyCode = e.keyCode || e.which;
			  if (keyCode === 13) { 
				e.preventDefault();
				return false;
			  }
			});
		});
	</script>
<?php endif; ?>
